// PNG Decoder Test Cases
// Expected pixel data for test images

const std = @import("std");

/// Test case: 1x1 grayscale image with gray value 128
/// File: test-data/1x1_grayscale.png
/// Generated by: tools/generate_test_data
pub const grayscale_1x1_expected = [_]u32{
    0x808080FF,  // gray=128 -> RGBA8888 (R=128, G=128, B=128, A=255)
};

/// Test case metadata
pub const TestCase = struct {
    name: []const u8,
    file_path: []const u8,
    width: u32,
    height: u32,
    expected_pixels: []const u32,
};

/// List of all test cases for Phase 1
pub const test_cases = [_]TestCase{
    TestCase{
        .name = "1x1 Grayscale",
        .file_path = "test-data/1x1_grayscale.png",
        .width = 1,
        .height = 1,
        .expected_pixels = &grayscale_1x1_expected,
    },
};
